#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 23 11:40:14 2023

@author: pablo
"""

import os
import numpy as np
os.chdir(os.path.dirname(os.path.abspath(__file__)))
import pandas as pd
from pyspark.sql import SparkSession
import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go


if st.checkbox("mostrar texto"):
    st.write("Hola")
    
spark = SparkSession.builder.getOrCreate()

dataframe_final = spark.read.csv("/_disk_dev/spyder/pages/dataframe_final.csv", header=True, inferSchema=True)
data = dataframe_final.toPandas()


####################################
##Fallecidos/Cantidad de pasajeros##
####################################


#limite_inferior_ratio_fatalities = st.slider("Definir limite inferior(Año)", 1970, 1980, 2021)
data_ratio_passengers = data[data['year'] > limite_inferior_ratio_fatalities]
diff_value_ratio_passengers = np.diff(data_ratio_passengers["ratio_passengers"], prepend=1)

diff_value_passengers = np.diff(data["ratio_passengers"], prepend=0)

# Crear el gráfico de cascada con plotly

fig_ratio_passengers = go.Figure(go.Waterfall(
    name="",
    orientation="v",
    x=data['year'].astype(str),
    y=diff_value_passengers,
    textposition="inside",
    #text=df['Valor'],
    connector={"line": {"color": "rgb(63, 63, 63)"}},
))

# Crear el gráfico de líneas

x_line = data['year']
y_line = data["ratio_passengers"]
fig_ratio_passengers.add_trace(go.Scatter(
    x=x_line,
    y=y_line,
    mode='lines',
    name='Línea',
    ))
    
    # Personalizar el gráfico
fig_ratio_passengers.update_layout(
    title="Ratio (Fallecidos / Cantidad de pasajeros)* 1.000.000",
    xaxis_title="Año",
    yaxis_title="cantidad accidentes por año",
)

st.plotly_chart(fig_ratio_passengers)
